- Publicity chair of <a href="https://wrla2024.gitlab.io">WRLA 2024</a>, 
  <a href="https://favpqc2023.gitlab.io/">FAVPQC 2023</a>, and
  <a href="https://favpqc2022.gitlab.io/">FAVPQC 2022</a>.

- PC member of <a href="https://icfem2026.github.io/">ICFEM 2026</a> and <a href="https://icfem2024.info/">ICFEM 2024</a>.

- PC member of <a href="https://ksiresearch.org/seke/seke26.html">SEKE 2026</a>.

- PC member of <a href="https://kse2026.kse-conferences.org/">KSE 2026</a> and <a href="https://kse2025.kse-conferences.org/">KSE 2025</a>.

- PC member of <a href="https://fmasworkshop.github.io/FMAS2026/">FMAS 2026</a>.

- Sub-reviewer of <a href="https://conf.researchr.org/home/fm-2026">FM 2026</a>,
  <a href="https://conf.researchr.org/home/Formalise-2025">FormaliSE 2025</a>, 
  <a href="https://abz-conf.org/2025/">ABZ 2025</a>,
  <a href="https://wrla2024.gitlab.io">WRLA 2024</a>, and 
  <a href="https://favpqc2022.gitlab.io/">FAVPQC 2022</a>.

- "Reviewer for several journals: Science of Computer Programming, 
  The Journal of Logical and Algebraic Methods in Programming,
  Computer Standards and Interfaces."
